### ISSUE TITLE
Mixed content in the AJonP Hugo Ionic demo on the Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [AJONPLLC/ajonp-hugo-ionic#2]
Hello @ajonp 

I am one of the people who maintain the Hugo Themes repository.

Recently I [had a look](https://github.com/gohugoio/hugoThemes/issues/532) at the deploy log of the Hugo Themes website and it seems that you have an insecure `http://` URL in your theme's demo that is throwing warnings about [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content):

In theme/[ajonp-hugo-ionic](https://themes.gohugo.io/ajonp-hugo-ionic/)/blog/welcome/index.html:

    Insecure img urls:
        http://res.cloudinary.com/ajonp/image/upload/f_auto,fl_lossy,q_auto/v1543499918/ajonp-ajonp-com/welcome/ajonp-ajonp-com-logo-round.png

Can you please change the above URL to `https`?

Please let me know.

Thanks!

**Comment by codercatdev** [comment]
Updated, please pull newest

**Comment by onedrawingperday** [comment]
Thank you for the fix.

The change will be shown the next time that themes are updated in the Hugo repository (usually happens about once a week).
